### PR TITLE
Remove nvmrc file

### PR DESCRIPTION
**Pull request by natebass**
Pull request 25 (https://github.com/code4sac/sacramento-campaign-finance/pull/25) adds [tabler](https://www.npmjs.com/package/@tabler/core) as an npm dependency. It requires node v18, whereas our application nvmrc specified v16.

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@tabler/core@1.0.0-beta20',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.1', npm: '8.19.4' }
npm WARN EBADENGINE }
```

I think we should remove the .nvmrc file to increase simplicity of the file structure. We could also update the file to a more recent version of node.

Let me know what you all think. Thanks.

### CODE REVIEW

**Comment by jeremiak** [comment]
Thanks for this @nmately! I don't think we should remove the `.nvmrc` file, I think we should replace the contents of the file with `18` or `20` (which ever version you're trying to use). The `.nvmrc` file makes it easy to use multiple versions of Node on your machine for different projects.

**Review by jeremiak — CHANGES_REQUESTED** [review]
Hey @natebass - thanks for this! I think we should keep the `.nvmrc` file and replace the contents with `18` or `20` (whichever version we're trying to install). `nvm` is a tool that helps developers use multiple versions of node on their machines for different projects to avoid dependency incompatibility with the `package-lock.json`.

Additionally, [Netlify uses](https://docs.netlify.com/configure-builds/manage-dependencies/) the `.nvmrc` file to know which version of node to use for deploying the site.

**Comment by natebass** [comment]
OK, sounds good.

I updated the file to Node 18.

**Comment by jeremiak** [comment]
Nice! Refs #26

**Review by jeremiak — APPROVED** [review]

**Pull request merged**
